version: "3.7"
services:
#  configserver:
#    build: ./config-server
#    restart: always
#    ports:
#      - "9101:9101"
  eurekaserver:
    build: ./eureka-server
    restart: always
    ports:
      - "9102:9102"
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: diabetecare
      MYSQL_USER: diabetecareusr
      MYSQL_PASSWORD: diabetecare123
      MYSQL_ROOT_PASSWORD: MysqlDockerRootP4ssW0rd!
  microservice_patients:
    container_name: mspatients
    build: ./microservice-patients
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
#      - configserver
      - eurekaserver
    command:
      - sh -c './wait-for mysql:3306 -- npm start'
