server:
    port: 8082

spring:
    application:
        name: 'microservice-patienthistory'
    data:
        mongodb:
            host: 'mongodb'
            port: '27017'
            database: 'diabetecare'
#            username: 'root'
#            password: 'root'
            auto-index-creation: 'true'


#Eureka
eureka:
    client:
        serviceUrl:
            defaultZone: 'http://eurekaserver:9102/eureka/'
        registerWithEureka: 'true'
        fetchRegistry: 'true'

#Personal configs
#Api version
api:
    ver: 'v1'
url:
    patient:
        proxy: "apigateway:8090/patient"

management:
    endpoints:
        web:
            exposure:
                include:
                    - mappings
                    - env
                    - health
                    - info