server:
  port: 8080

spring:
  application:
    name: 'microservice-report'

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9102/eureka/'
    registerWithEureka: 'true'
    fetchRegistry: 'true'

#Personal configs
#Api version
api:
  ver: 'v1'
url:
  patient:
    proxy: "localhost:8090/patient"
  patientHistory:
    proxy: "localhost:8090/patHistory"

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
