#Server
server:
  port: 9101

#Spring
spring:
  application:
    name: 'config-server'
  cloud:
    compatibility-verifier:
      enabled: 'false'
    config:
      server:
        bootstrap: 'true'
        git:
          default-label: 'main'
          uri: 'https://github.com/elienFR/OC_P9_diabeteCare_config_repo'



