#Server
server:
  port: 9101

#Spring
spring:
  application:
    name: 'config-server'
  cloud:
    compatibility-verifier:
      enabled: 'false'
    config:
      server:
        bootstrap: 'true'
        default-label: 'develop'
        uri: 'https://github.com/elienFR/OC_P8_diabeteCare/tree/main/config-server-repo'



